### ISSUE TITLE
Module with dots in name are not openable in `v4.1.0`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#26]
I upgraded to `v4.1.0`.

After I click in the sidebar on a module with a dot `.` in the module name, this exception occurs and nothing happens. Other modules, without a dot, seems to work.

```javascript
index-QGoXRsv3.js:1 TypeError: Cannot read properties of undefined (reading 'replace')
    at Proxy.a (index-QGoXRsv3.js:10:46603)
    at onClick (index-QGoXRsv3.js:10:49067)
    at vn (index-QGoXRsv3.js:1:17624)
    at Rt (index-QGoXRsv3.js:1:17703)
    at HTMLDivElement.n (index-QGoXRsv3.js:1:80004)
```

**Comment by akelch** [comment]
Fixed with the next version: https://github.com/viur-framework/vi-vue-components/commit/2896cd9eb412e82893fc3b5ca1c5e1c812d9e1ee
