### ISSUE TITLE
Cannot select columns

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#28]
In a list view a click in on _"Felder"_ does nothing.

But, on the console I found this error:
```js
3index-BrsNanUB.js:1 TypeError: Cannot read properties of undefined (reading 'structure')
    at Proxy.r (index-BrsNanUB.js:10:71830)
    at k.onClick.t.<computed>.t.<computed> (index-BrsNanUB.js:10:72907)
    at vn (index-BrsNanUB.js:1:17624)
    at Dt (index-BrsNanUB.js:1:17703)
    at e.n (index-BrsNanUB.js:1:80004)
```

It does not work in a nested module with a dot, neither in a normal

**Comment by sveneberth** [comment]
The field selection works again, but the first time the fields are not selected, the second time they are.

**Comment by sveneberth** [comment]
is now working
