### ISSUE TITLE
doubleclick on an entry in a list doesnt open the edit pane

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#36]
causing this error
```
index-zZThdHBr.js:1 TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Proxy.$ (index-zZThdHBr.js:12:40140)
    at C.onDblclick.t.<computed>.t.<computed> (index-zZThdHBr.js:12:44638)
    at vn (index-zZThdHBr.js:1:17705)
    at Mt (index-zZThdHBr.js:1:17784)
    at HTMLTableRowElement.n (index-zZThdHBr.js:1:80125)
Pp @ index-zZThdHBr.js:1
ms @ index-zZThdHBr.js:1
vn @ index-zZThdHBr.js:1
Mt @ index-zZThdHBr.js:1
n @ index-zZThdHBr.js:1
```

but only in few modules

**Comment by sveneberth** [comment]
Works for me in `v4.6.5`
