### ISSUE TITLE
bug: Edit selected RelationBone Skel (foreign entity) not working

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/vi-admin#42]
Just a error on the console, but nothing happens
```js
index-Iwo5i3Bl.js:14 TypeError: Cannot read properties of undefined (reading 'type')
    at Proxy.y (index-Iwo5i3Bl.js:35:32579)
    at S5.e.state.selection.e.boneState.isEmpty.C.onClick.t.<computed>.t.<computed> (index-Iwo5i3Bl.js:35:33737)
    at kn (index-Iwo5i3Bl.js:14:1373)
    at Bt (index-Iwo5i3Bl.js:14:1444)
    at e.n (index-Iwo5i3Bl.js:18:8227)
```

I clicked the left button:
![image](https://github.com/viur-framework/vi-admin/assets/10272292/f63dc8dd-13ff-42e0-8e04-4ea6461983f6)

(Still not working with v4.3.0)

**Comment by sveneberth** [comment]
Works for me in `v4.6.5`
